### ISSUE TITLE
Bug report: AES Encryption

### ISSUE THREAD

**Issue by aawheatley** [gchq/CyberChef#1013]
**Describe the bug**
When trying to encrypt a string using **AES Encrypt** and adding a key (either 16, 24 or 32 bytes) it gives an error. You can see the image I will attach later.

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

![gchq-error](https://user-images.githubusercontent.com/53082621/79336671-71062600-7f24-11ea-859d-e7959fbdf0ec.png)

**Comment by aawheatley** [comment]
Changing all the zeros for other characters makes the same error.

**Comment by n1073645** [comment]
Most AES modes require a non-empty initialisation vector to be considered secure, the exception to that is ECB mode since it doesn't intermix the output of a block with the next plaintext block.

![image](https://user-images.githubusercontent.com/57447333/79474971-01189e00-7fff-11ea-91be-4fb60864a0fc.png)

CBC(the mode in this case) does intermix the plaintext block with the output of the previous encrypted block. Hence, to initiate this process for the first plaintext block, an additional input value is required to be mixed with the first block, and which is referred to as an initialisation vector(IV).

![image](https://user-images.githubusercontent.com/57447333/79475092-23aab700-7fff-11ea-9491-56f13bd6ce43.png)

**Comment by dsmackie** [comment]
Both AES encrypt and decrypt operations state the following; 

**The Initialization Vector should be 16 bytes long. If not entered, it will default to 16 null bytes.**

Since it does **not** default to 16 bytes long when left empty the above text should be modified to reflect this updated requirement.

**Comment by owlstead** [comment]
Uh, how exactly was this resolved?
