### ISSUE TITLE
Bug report: Remove Diacritics polish "Łł"

### ISSUE THREAD

**Issue by hermozol21** [gchq/CyberChef#1020]
**Describe the bug**
Polish diacritic letter "Ł" and lowercase "ł" are not replaced with "L" and "l" in "Remove Diacritic"

**To Reproduce**

1. Go to '"Remove Diacritic"

**Expected behaviour**
Replace polish "Ł" and "ł" for "L" and "l"

**Screenshots**
![image](https://user-images.githubusercontent.com/64005792/79734703-70400c00-82f7-11ea-9f46-4aaec62af62d.png)

**Desktop (if relevant, please complete the following information):**
 - OS:  Windows
 - Browser: firefox 75
 - CyberChef version: 9.20.3

**Additional context**

**Comment by mattnotmitt** [comment]
Based on the discussion [here](https://stackoverflow.com/questions/990904/remove-accents-diacritics-in-a-string-in-javascript/37511463) it seems that it's generally accepted that Polish "diacritics" are actually member letters of the alphabet, unlike French for example. We could add it as a specific case.

**Comment by n1474335** [comment]
Given that there are a lot of characters that will fall into this category, and it doesn't seem sensible to write special cases for them all, we will not add this as a special case. If it is technically a letter in its own right, rather than something with a diacritic applied, then this operation will not change it.

If you really need to change this specific letter, a Find/Replace operation can easily be added to the recipe.

Thanks for raising the issue.
