### ISSUE TITLE
Bug report: Can't get AND to work as expected

### ISSUE THREAD

**Issue by matt-coding** [gchq/CyberChef#1027]
**Describe the bug**
I have a character, 'A' in this case, which I convert to binary, I send this via AND. 

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

https://gchq.github.io/CyberChef/#recipe=To_Binary('None')AND(%7B'option':'Binary','string':'00001111'%7D)&input=QQ

**Expected behaviour**
I would expect the output to be "00000001".

Please let me know if I need to do something differently.

**Comment by n1073645** [comment]
The output of ToBinary is actually a string so each 1 and 0 is a separate character. Your AND operation operates on each of those characters rather than the single A.

For what you need:
[https://gchq.github.io/CyberChef/#recipe=AND(%7B'option':'Binary','string':'00001111'%7D)To_Binary('Space')&input=QQ](url)
