### ISSUE TITLE
From Base85/Ascii85 not decoding properly or missing the adobe alphabet 

### ISSUE THREAD

**Issue by tvfischer** [gchq/CyberChef#1057]
**Describe the bug**
When using From Base85, the following cipher text is not decode and gives an error. The text below follows the normal Adobe/Ascii encoding
```
<~<+ohc@UX=l@j#Z#ARloqDfQt/+C]&&@<-WFFDiaQAU&;>ASu!rA8,po+Cf>,ATJu+Ec5e;@3BH!ARl
p*D]iP.D/FE5Bk(RnAKYE%@VKq)@<-W9@VK^gEd8d<@<>p#Dg#]4+E2@4AU%p1FD5W*+Cf>,D09`1@ps
InDf0V=E,ol=De!^%F!,R<@<<W9ATD?)A7]grB5V9k+EVNE@psCuGp%$CCj@-lDJ*d"F(c\4@;]_#@:s
-oBQ\0#DCom?@:WeUCh4`2AU&;L+B3#mF(HJ(Df'?6DJ<ThFD5Z2+E2@>FDkZ-Ci^_9@<iu6DJXS@@V$
Z@/RiF9+ELt'AKWC0DIal6Bln$&DBO%7@<<W#G&M)*+Ceu'FCAm$+@/pn8P(%7Df0Z;DepP+De*F#.4c
TMDIal,@<iu9AT;j,Eb-A0Bl7K)@WH$gCNCV,F<G()Ecb`(DBNe)G\M#;D'3P1FCfK9@;L!9+CT.u+Dk
P4+Du+>+DkP$DKK<$DBO.:Blmp-E+*6f/g+,,F`T)VDf0B:+EV:.+?;;%E,oZ1FCAWpAKX9;6V0il@q]
:k@:OCjEcW@3Eb-@;F(&Zl+s:uG+E_a:+EVNE@rH7.AU,D/@<>p1+B3#c+D,FuB-:o0+>@54Ai;PXAR[
MU2.SO"ARf=`1h&<t0JtRB2e4d%3+b$)AN)P[0Jt[G@5D@OAMl1t2.gE.11;t!3AkD&@P/c1~>
```

The error given is `From Base85 - Invalid character '~' at index 1`

If you remove the **<~** and **~>** the following error is given `From Base85 - Invalid character ' ' at index 3`

The text decodes to this on other online decoders:
```
The basic need for a binary-to-text encoding comes from a need to communicate arbitrary binary data over preexisting communications protocols that were designed to carry only English language human-readable text. Those communication protocols may only be 7-bit safe (and within that avoid certain ASCII control codes), and may require line breaks at certain maximum intervals, and may not maintain whitespace. Thus, only the 95 printable ASCII characters are "safe" to use to convey data. The flag is 0aaf66deb575d43ecfe4b5205157d538f54e77f0547a3b7e5125fea2a3995f0b.
```

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

1. Open cyberchef  (Version 9.21.0 Compile time: 12/06/2020 12:53:19 UTC at time of bug)
2. Paste encrypt text into input field
```
<~<+ohc@UX=l@j#Z#ARloqDfQt/+C]&&@<-WFFDiaQAU&;>ASu!rA8,po+Cf>,ATJu+Ec5e;@3BH!ARl
p*D]iP.D/FE5Bk(RnAKYE%@VKq)@<-W9@VK^gEd8d<@<>p#Dg#]4+E2@4AU%p1FD5W*+Cf>,D09`1@ps
InDf0V=E,ol=De!^%F!,R<@<<W9ATD?)A7]grB5V9k+EVNE@psCuGp%$CCj@-lDJ*d"F(c\4@;]_#@:s
-oBQ\0#DCom?@:WeUCh4`2AU&;L+B3#mF(HJ(Df'?6DJ<ThFD5Z2+E2@>FDkZ-Ci^_9@<iu6DJXS@@V$
Z@/RiF9+ELt'AKWC0DIal6Bln$&DBO%7@<<W#G&M)*+Ceu'FCAm$+@/pn8P(%7Df0Z;DepP+De*F#.4c
TMDIal,@<iu9AT;j,Eb-A0Bl7K)@WH$gCNCV,F<G()Ecb`(DBNe)G\M#;D'3P1FCfK9@;L!9+CT.u+Dk
P4+Du+>+DkP$DKK<$DBO.:Blmp-E+*6f/g+,,F`T)VDf0B:+EV:.+?;;%E,oZ1FCAWpAKX9;6V0il@q]
:k@:OCjEcW@3Eb-@;F(&Zl+s:uG+E_a:+EVNE@rH7.AU,D/@<>p1+B3#c+D,FuB-:o0+>@54Ai;PXAR[
MU2.SO"ARf=`1h&<t0JtRB2e4d%3+b$)AN)P[0Jt[G@5D@OAMl1t2.gE.11;t!3AkD&@P/c1~>
```
3. Drag **From Base85** to recipe

Playing with the Alphabet setting provides different errors

**Additional context**
Following is some more details and example decoder

- https://www.tools4noobs.com/online_tools/ascii85_decode/
- https://en.wikipedia.org/wiki/Ascii85

**Comment by n1073645** [comment]
It errors because of the line feeds(\n) in the input. When pull request #1033 gets merged it will fix this behaviour.

For now, the following works:

[https://gchq.github.io/CyberChef/#recipe=Remove_whitespace(false,false,true,false,false,false)From_Base85('!-u')&input=PH48K29oY0BVWD1sQGojWiNBUmxvcURmUXQvK0NdJiZAPC1XRkZEaWFRQVUmOz5BU3UhckE4LHBvK0NmPixBVEp1K0VjNWU7QDNCSCFBUmwKcCpEXWlQLkQvRkU1QmsoUm5BS1lFJUBWS3EpQDwtVzlAVkteZ0VkOGQ8QDw%2BcCNEZyNdNCtFMkA0QVUlcDFGRDVXKitDZj4sRDA5YDFAcHMKSW5EZjBWPUUsb2w9RGUhXiVGISxSPEA8PFc5QVREPylBN11nckI1VjlrK0VWTkVAcHNDdUdwJSRDQ2pALWxESipkIkYoY1w0QDtdXyNAOnMKLW9CUVwwI0RDb20/QDpXZVVDaDRgMkFVJjtMK0IzI21GKEhKKERmJz82REo8VGhGRDVaMitFMkA%2BRkRrWi1DaV5fOUA8aXU2REpYU0BAViQKWkAvUmlGOStFTHQnQUtXQzBESWFsNkJsbiQmREJPJTdAPDxXI0cmTSkqK0NldSdGQ0FtJCtAL3BuOFAoJTdEZjBaO0RlcFArRGUqRiMuNGMKVE1ESWFsLEA8aXU5QVQ7aixFYi1BMEJsN0spQFdIJGdDTkNWLEY8RygpRWNiYChEQk5lKUdcTSM7RCczUDFGQ2ZLOUA7TCE5K0NULnUrRGsKUDQrRHUrPitEa1AkREtLPCREQk8uOkJsbXAtRSsqNmYvZyssLEZgVClWRGYwQjorRVY6Lis/OzslRSxvWjFGQ0FXcEFLWDk7NlYwaWxAcV0KOmtAOk9DakVjV0AzRWItQDtGKCZabCtzOnVHK0VfYTorRVZORUBySDcuQVUsRC9APD5wMStCMyNjK0QsRnVCLTpvMCs%2BQDU0QWk7UFhBUlsKTVUyLlNPIkFSZj1gMWgmPHQwSnRSQjJlNGQlMytiJClBTilQWzBKdFtHQDVEQE9BTWwxdDIuZ0UuMTE7dCEzQWtEJkBQL2Mxfj4](url)
