### ISSUE TITLE
Misc: remove nerd comments from loader

### ISSUE THREAD

**Issue by innovate-support** [gchq/CyberChef#1180]
I was working through our Security Onion system with a coworker today and he opened CyberChef. During the loading spinner it showed an alarming message about Bitcoin Mining. After some investigation it seems that it's just nerd code that's been inserted on purpose as a joke. But this is not cool to have popup in a security tool's interface. I suggest you remove these comments and just have a normal loader with no text.

Here's the messages listed in the header code.

"Proving P = NP...",
"Computing 6 x 9...",
"Mining bitcoin...",
"Dividing by 0...",
"Initialising Skynet...",
"[REDACTED]",
"Downloading more RAM...",
"Ordering 1s and 0s...",
"Navigating neural network...",
"Importing machine learning...",
"Issuing Alice and Bob one-time pads...",
"Mining bitcoin cash...",
"Generating key material by trying to escape vim...",
"for i in range(additional): Pylon()",
"creating unresolved tension...",
"Symlinking emacs and vim to ed...",
"Training branch predictor...",
"Timing cache hits...",
"Speculatively executing recipes..."

**Comment by mattnotmitt** [comment]
Since when is fun banned in the workplace? Joking aside, if you want a version of the program without that, there's instructions to compile it yourself in the wiki - just replace the array of those messages with just "Loading CyberChef" or something equally innocuous and then your colleague won't be spooked.

**Comment by n1474335** [comment]
Humorous loading messages are quite common in a number of tools so I'm not convinced removing them from CyberChef is really required.

That said, CyberChef is an open source tool, so if you would like to fork it and create your own levity-free version, you are more than welcome.

**Comment by Gitoffthelawn** [comment]
I enjoy humour quite a bit, but I concur with the OP that it is best to remove these messages.

I hadn't used CyberChef in a while, and when I visited it recently, it displayed a message claiming it was mining bitcoin.

Did this mean CyberChef source code was hacked?  What about the server itself?  Was there a DNS record modification?  Did CyberChef sell out to some bitcoin hive mining enterprise?  Did someone forgot to remove a silly debug message?  Was it something else?

This message resulted in me engaging in an immediate security checkup, checking the DNS records for changes, and reading the source code for the site.  That's where I saw the messages in the code, which then led me here to see if it was intentional or if a jokester got a PR accepted that should never have been accepted.

Well, I'm a bit surprised that the code remains and that the first response was "Since when is fun banned in the workplace?" followed by, essentially, a nicely put "if you don't like it, go build it yourself".  Thankfully, that's not why most people put projects on GitHub.  Most people put projects on GitHub because they value constructive user feedback, bug reports, and often, pull requests.

The second response is more helpful.  It provides the rationale for the code and the reason why it was not deleted at that time.  I respect both.  At the same time, I truly enjoy humour, but I don't think any of these those messages are particularly funny.  Well, *"Ordering 1s and 0s..."* is a little bit cute. ;)
