### ISSUE TITLE
Bug report: Running the project locally

### ISSUE THREAD

**Issue by erikkamph** [gchq/CyberChef#1205]
**Describe the bug**
The bug is that cyberchef when started with `npm start` can not find a module called "OpModules.mjs" when accessed from Firefox in Parrot OS.

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

1. Start a virtual machine with Parrot OS installed
2. Download latest version of the project.
3. Open a terminal in the project folder.
4. Run `npm install`
5. Run `npm audit fix`
6. Run `npm start`
7. Open Firefox and go to `http://0.0.0.0:8080/`
8. See the errors in Firefox and Terminal.

**Expected behaviour**
My expectation was to be able to run the project locally on my virtual machine whenever I have a slow internet connection, since it will be faster running it locally.

**Screenshots**
<img width="2048" alt="Screenshot 2021-06-03 at 13 16 01" src="https://user-images.githubusercontent.com/48324322/120637845-af83da80-c46f-11eb-898d-0c0f73ebae7c.png">
<img width="695" alt="Screenshot 2021-06-03 at 13 36 04" src="https://user-images.githubusercontent.com/48324322/120638666-b19a6900-c470-11eb-8b14-054a46692078.png">
<img width="695" alt="Screenshot 2021-06-03 at 13 36 09" src="https://user-images.githubusercontent.com/48324322/120638701-bf4fee80-c470-11eb-8518-ae48d5154578.png">

**Desktop (if relevant, please complete the following information):**
- Host OS: macOS
- Host OS Version: 11.4
- Application: VMWare Fusion
- Application Version: 12.1.2
- Guest OS: Parrot OS
- Guest OS Version: 4.11
- Guest OS Browser: Firefox
- Guest OS Browser Version: 78.0
- Guest OS Terminal: Konsole
- Guest OS Terminal Version: 20.12.3

**Comment by sganson-tss** [comment]
What version of Node are you running?

From: Erik Kamph ***@***.***>
Sent: Thursday, June 3, 2021 5:16 PM
To: gchq/CyberChef ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gchq/CyberChef] Bug report: Running the project locally (#1205)


Describe the bug
The bug is that cyberchef when started with npm start can not find a module called "OpModules.mjs" when accessed from Firefox in Parrot OS.

To Reproduce
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

  1.  Start a virtual machine with Parrot OS installed
  2.  Download latest version of the project.
  3.  Open a terminal in the project folder.
  4.  Run npm install
  5.  Run npm audit fix
  6.  Run npm start
  7.  Open Firefox and go to http://0.0.0.0:8080/
  8.  See the errors in Firefox and Terminal.

Expected behaviour
My expectation was to be able to run the project locally on my virtual machine whenever I have a slow internet connection, since it will be faster running it locally.

Screenshots
[Screenshot 2021-06-03 at 13 16 01]<https://user-images.githubusercontent.com/48324322/120637845-af83da80-c46f-11eb-898d-0c0f73ebae7c.png>
[Screenshot 2021-06-03 at 13 36 04]<https://user-images.githubusercontent.com/48324322/120638666-b19a6900-c470-11eb-8b14-054a46692078.png>
[Screenshot 2021-06-03 at 13 36 09]<https://user-images.githubusercontent.com/48324322/120638701-bf4fee80-c470-11eb-8518-ae48d5154578.png>

Desktop (if relevant, please complete the following information):

  *   Host OS: macOS
  *   Host OS Version: 11.4
  *   Application: VMWare Fusion
  *   Application Version: 12.1.2
  *   Guest OS: Parrot OS
  *   Guest OS Version: 4.11
  *   Guest OS Browser: Firefox
  *   Guest OS Browser Version: 78.0
  *   Guest OS Terminal: Konsole
  *   Guest OS Terminal Version: 20.12.3

**Comment by erikkamph** [comment]
Node version is 12.21.0
npm version is 7.5.2

**Comment by mt3571** [comment]
Try downgrading to Node v10, see [this issue](https://github.com/gchq/CyberChef/issues/1165) and the [README](https://github.com/gchq/CyberChef/#nodejs-support) for more info.
