### ISSUE TITLE
Bug report: The way to handle invalid base64 input doesn't look good

### ISSUE THREAD

**Issue by mikecat** [gchq/CyberChef#1254]
**Describe the bug**

First problem I found is that an unkindful (looks internal) message

```
Data is not a valid byteArray: [105,166,154,260]
```

is shown when I try to "From Base64"

```
aaaa=
```

**To Reproduce**

[From Base64 - CyberChef](https://gchq.github.io/CyberChef/#recipe=From_Base64%28%27A-Za-z0-9%2B/%3D%27,true%29&input=YWFhYT0)

**Expected behaviour**

Either one of:

* See kindful error message like "invalid base64 input", "invalid usage of padding character in base64 decoding", etc.
* Yield some valid byte array. (for example, by treating misused padding characters as encoding zero instead of 64)

**Desktop (if relevant, please complete the following information):**
 - OS: Windows 10 Home x64
 - Browser: Firefox Browser 92.0.1 (x64)
 - CyberChef version: 9.32.3

"REPORT A BUG" tab information:

* Version: 9.32.3
* Compile time: 03/09/2021 14:01:00 UTC
* User-Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0
* [Link to reproduce](https://gchq.github.io/CyberChef/#recipe=From_Base64('A-Za-z0-9%2B/%3D',true)&input=YWFhYT0)

**Additional context**

The data seems marked as invalid bacause there is an element "260", which exceeds 255.

Reading the code [`fromBase64`](https://github.com/gchq/CyberChef/blob/master/src/core/lib/Base64.mjs#L85) in `src/core/lib/Base64.mjs`, I found that the characters are not checked well and exceeding number can be generated when the first character in the 4-character group is a padding character.
The padding character is decoded as 64 in the current implementation, and the value is put into the decoded "byte" without being masked, so this can be a cause of generation of out-of-range value.

I think the message "Data is not a valid byteArray" shouldn't be exposed to users because it is about the internals of CyberChef and users may find it hard to understand. Moreover, it looks unclear what the "Data" in the message means without reading the code.

I decided not to simply send a pull request because there seems a design choice here to improve from here.
Choices I came up with are:

* Add check for invalid base64 input and throw some exception for invalid input.
  What to check should include:
  * misuse of the padding character or non-alphabet characters like using padding characters in the middle of input
  * input with length 1 modulo 4, excluding the last padding characters
* Yield some (valid) sequences of bytes like it did in some other invalid inputs like `a==a`
  * This can be achieved by, for example, adding mask to `enc1` when constructing the output.

Do you think which is better?

**Comment by mikecat** [comment]
I created a pull request to add Base64 input validation.
Please let me know if there are some reasons to allow malformed input for `fromBase64()`.

**Comment by n1474335** [comment]
Thanks very much for looking into this. I completely agree that the error message "Data is not a valid byteArray" is particularly opaque and unhelpful to the user. It pops up in a number of scenarios when the data isn't in a format that CyberChef can convert properly. It should always be caught by an operation and converted into a more helpful message - at least that is the aspiration!

The checks you added are really helpful. I've modified them a little so that they only show up when the user specifies 'Strict mode' on the 'From Base64' operation. CyberChef is designed to handle all sorts of strange input, much of which won't be in a perfectly defined format. I believe it is useful if it can still show something of use rather than error continuously until you have all your ducks in a row. However, supporting a strict mode that shows you exactly what is wrong and how it is wrong, is obviously helpful.

I have added some checks that prevent the `fromBase64` function from returning invalid data (which is what was causing the opaque error message). It will now discard decoded byte values that are outside of the valid range for a byte (>255). I believe this is the most sensible solution since it seems to always be caused by the padding character being used in the wrong place, which feels like something that can be ignored if you don't want it to error. Enabling 'Strict mode' will highlight this problem rather than discarding it.
