### ISSUE TITLE
Bug report:  Bug when decoding VBA style formatted hex (&H notation)

### ISSUE THREAD

**Issue by tlansec** [gchq/CyberChef#1285]
**Describe the bug**
When VBA notation hex is used with the recipe 'From Hex' on auto setting, it gives the impression it is working correctly, but infact fails to parse the data correctly.

**To Reproduce**
1. "&H55,&H8B,&HEC,&H81,&HEC,&H90,&H0,&H0,&H0,&H56,&H57,&HB9,&H4C,&H77"1
2. Add the following to the recipe: "From Hex" -> To Hex

**Expected behaviour**
The console should show the following hex output:

55 8B EC 81 EC 90 00 00 00 56 57 B9 4C 07 

Actual output shown is:

55 8B EC 81 EC 90 00 05 65 7B 94 C7

This is because the VBA style hex notation allows for hex 0x0 (rather than 0x00) style notation. The logic for the auto mode could be adjusted to handle this in the following way (python):

```
input_string ='&H55,&H8B,&HEC,&H81,&HEC,&H90,&H0,&H0,&H0,&H56,&H57,&HB9,&H4C,&H77'
current_hex_str = ''
hex_to_decode = ''
valid_hex_chars = 'abcdef0123456789'
for char in input_string.lower():
    if char not in valid_hex_chars:
        if len(current_hex_str) != 2 and len(current_hex_str) > 0:

            current_hex_str = "0" + current_hex_str
        hex_to_decode += current_hex_str
        current_hex_str = ''
    else:
        current_hex_str=  current_hex_str + char

print(hex_to_decode)
```

That way it doesnt matter if the notation used uses single chars or multi chars to denote 0x0, 0x00 etc.

Cheers,
Tom

**Comment by mikecat** [comment]
This issue is not VBA notation-specific but can happen with simple space-delimited data.

[From Hex, To Hex - CyberChef](https://gchq.github.io/CyberChef/#recipe=From_Hex%28%27Space%27%29To_Hex%28%27Space%27,0%29&input=NTUgOEIgRUMgODEgRUMgOTAgMCAwIDAgNTYgNTcgQjkgNEMgNzc)

Workaround: split the data and convert each values.

[Fork, From Hex, Merge, To Hex - CyberChef](https://gchq.github.io/CyberChef/#recipe=Fork%28%27%26H%27,%27%27,false%29From_Hex%28%27Auto%27%29Merge%28%29To_Hex%28%27Space%27,0%29&input=Jkg1NSwmSDhCLCZIRUMsJkg4MSwmSEVDLCZIOTAsJkgwLCZIMCwmSDAsJkg1NiwmSDU3LCZIQjksJkg0QywmSDc3)
