### ISSUE TITLE
Cannot add value as number.

### ISSUE THREAD

**Issue by wgf4242** [gchq/CyberChef#1292]
Input 
```
12
15
```
Add 3, Got 
```
45
48
```

Expected
```
15
18
```

How to do this?

Solved by:  convert to bytes -> add value -> convert to string:
https://gchq.github.io/CyberChef/#recipe=Fork('%5C%5Cn','%5C%5Cn',false)From_Decimal('Space',false)ADD(%7B'option':'Hex','string':'3'%7D)To_Decimal('Space',false)&input=MTIKMTU

**Comment by Bri-ish** [comment]
This wouldn't be an issue as such, but more a misunderstanding. What I've learnt from a bit of messing around is that the standard input type is ASCII, therefore each character/digit is represented by a byte. The ADD function is a bit-wise addition function therefore by adding 3 you are adding three to each digit's byte hence you get 4 and 5.

Therefore when you, for instance, add 8 to 12 you are adding:
(8hex/dec) = 00001000 to
(1ascii) = 00110001 and
(2ascii) = 00110010
which results in 00111001 and 00111010 which are "9:" in ASCII which is what you get when you actually put it in.

It's confusing at first but after messing around with it a bit you'll get the hang of it.
I've not yet figured out how to add it as decimal and decimal just because the conversion of ASCII to decimal isn't direct but I'm sure it's possible and if it isn't, I'm sure it'll get added :)

**Comment by Bri-ish** [comment]
> Input
> 
> ```
> 12
> 15
> ```
> 
> Add 3, Got
> 
> ```
> 45
> 48
> ```
> 
> Expected
> 
> ```
> 15
> 18
> ```
> 
> How to do this?

This wouldn't be an issue as such, but more a misunderstanding. What I've learnt from a bit of messing around is that the standard input type is ASCII, therefore each character/digit is represented by a byte. The ADD function is a bit-wise addition function therefore by adding 3 you are adding three to each digit's byte hence you get 4 and 5.

Therefore when you, for instance, add 8 to 12 you are adding:
(8hex/dec) = 00001000 to
(1ascii) = 00110001 and
(2ascii) = 00110010
which results in 00111001 and 00111010 which are "9:" in ASCII which is what you get when you actually put it in.

It's confusing at first but after messing around with it a bit you'll get the hang of it.
I've not yet figured out how to add it as decimal and decimal just because the conversion of ASCII to decimal isn't direct but I'm sure it's possible and if it isn't, I'm sure it'll get added :)

**Comment by mikecat** [comment]
Addition of number doesn't look exist, but subtraction of number exists.

You can add 3 by subtracting -3.

[Fork, Find / Replace, Subtract - CyberChef](https://gchq.github.io/CyberChef/#recipe=Fork%28%27%5C%5Cn%27,%27%5C%5Cn%27,false%29Find_/_Replace%28%7B%27option%27:%27Regex%27,%27string%27:%27$%27%7D,%27%20-3%27,true,false,true,false%29Subtract%28%27Space%27%29&input=MTIKMTU)

**Comment by mikecat** [comment]
@Bri-ish

There is one more trick here: the newline character 0x0a becomes 0x0d by being added 3, so it still represents a newline.

Adding another value like 2 or 4 won't work like this.
