### ISSUE TITLE
Error while Decompression in CyberChef

### ISSUE THREAD

**Issue by lbhardwaj** [gchq/CyberChef#133]
I compressed a base 64 text using ZIP in cyberchef and when I open the cyberchef in a new sessionto decompress the same compressed Text format it throws an error "END OF CENTRAL CIRECTORY RECORD NOT FOUND". Can anyone help me with this erro in CyberChef?

**Comment by n1474335** [comment]
Hi @lbhardwaj, there are a number of ways this error could have come about. From the way you've described it, I suspect it's due to you copying over the raw output of the Zip operation into a new instance of CyberChef. Some bytes are not printable, so CyberChef replaces them with dots (.) to allow users to see that there is an unprintable byte there. This means that if you just copy that raw output, you will lose the actual values of those bytes, which will make unzipping the data impossible and lead to the error message you described. If you need to copy the zip output somewhere, you should either convert it to a text-based format like hexadecimal or base64, or save it to a file.

I hope this solves your problem. If not, please let us know and include the input and recipe which can replicate the error.
