### ISSUE TITLE
Operation request: Url Fetch

### ISSUE THREAD

**Issue by ErikRospo** [gchq/CyberChef#1366]
## Summary
Fetch data from a url, and use it as an output

### Example Input
`https://example.com/`
### Example Output
`
<!doctype html>
<html>
<head>
    <title>Example Domain</title>

    <meta charset="utf-8" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
`...

**Comment by n1474335** [comment]
Hi @ErikRospo,

This already exists in the 'HTTP request' operation. Here's an example: https://gchq.github.io/CyberChef/#recipe=HTTP_request('GET','https://worldtimeapi.org/api/timezone/Europe/London','','Cross-Origin%20Resource%20Sharing',false)JSON_Beautify('%20%20%20%20',false,true)

Unfortunately, due to Cross-Origin Resource Sharing issues, most websites won't support this, so it can't be used in lieu of something like wget or curl. It's really only useful for globally accessible APIs, like the example above. There's not a lot we can do to get around this. If we could, it would become a fairly major security risk.
