### ISSUE TITLE
Bug report: SyntaxError: Unexpected token 

### ISSUE THREAD

**Issue by jaswinder97** [gchq/CyberChef#1383]
**Describe the bug**
Getting many syntax error while running `grunt prod` for node version 8.x:

`Loading "eslint.js" tasks...ERROR
>> SyntaxError: Unexpected token {
Loading "webpack-dev-server.js" tasks...ERROR
>> ReferenceError: BigInt is not defined
Loading "webpack.js" tasks...ERROR
>> ReferenceError: BigInt is not defined
Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Unexpected token import
Warning: Task "eslint" not found. Use --force to continue.

Aborted due to warnings.
`

**To Reproduce**
Steps to reproduce the behaviour or a link to the recipe / input used to cause the bug:

1. git clone https://github.com/gchq/CyberChef.git
2. nvm use 16
3. npm install
4. npm rebuild node-sass
5. grunt prod

**Expected behaviour**
It should generate production build at path build/prod

**Screenshots**

**Desktop (if relevant, please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS 
 - Browser: Chrome
 - CyberChef version: [e.g. 9.46]

![Screenshot from 2022-07-21 14-27-40](https://user-images.githubusercontent.com/17950241/180174181-0e7b5664-c9a9-49ff-b859-566fe96794ca.png)

**Comment by n1474335** [comment]
1. Install nvm (https://github.com/nvm-sh/nvm)
2. `nvm install 18`
3. Pull down the latest version of CyberChef
4. `npm install`
5. `npm run build` (for a production version) or `npm start` (for the dev version)

Closing this for now since there have been a lot of improvements since this issue was raised and they should have sorted this out for you. If you're still getting issues, please reopen this ticket.
