### ISSUE TITLE
Bug report: wrong AES ciphertext output

### ISSUE THREAD

**Issue by Kebechet** [gchq/CyberChef#1412]
**Describe the bug**
I am not an advanced crypto user but AES specification tells that input length should be the same as the output cipher text. What is not true in my case. For some strange reason output contains my expected result+some additional data.
[This site](http://aes.online-domain-tools.com/) returns result I expect.

**To Reproduce**
[recipe](https://gchq.github.io/CyberChef/#recipe=AES_Encrypt(%7B'option':'Hex','string':'F611A1111C1111A111161E1116111111'%7D,%7B'option':'Hex','string':''%7D,'ECB','Hex','Hex',%7B'option':'Hex','string':''%7D)&input=MTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMjI)

**Expected behavior**
I expect to have return value as following:
`cf41f61a190f8e38b9cb102874d95a47`

**Screenshots**
https://gchq.github.io/
![image](https://user-images.githubusercontent.com/37485681/188918956-8d30c2ee-080a-4ca7-bc08-23666cc612f5.png)
http://aes.online-domain-tools.com/
![image](https://user-images.githubusercontent.com/37485681/188920543-79768d8a-04a9-42ac-8399-22a26696c1fa.png)

**Desktop:**
 - OS: Windows 10.0.19043 Build 19043
 - Browser: Google Chrome | 105.0.5195.102 (Official Build) (64-bit) (cohort: 105_Win_102)
 - CyberChef version: 9.46.0

**Comment by Kebechet** [comment]
Ok, I found out it is just padding, but why the padding is appended when the data length have size exactly one block ? And the second block is fully padded ?

**Comment by mikecat** [comment]
It should be because PKCS is defined so (16-byte padding is added when the length of the plaintext is multiple of 16).

[PKCS padding method - IBM Documentation](https://www.ibm.com/docs/en/zos/2.4.0?topic=rules-pkcs-padding-method)

I think it is not to confuse between (for example) "a 16-byte message with 0x01 as the last byte)" and "a 15-byte message with 0x01 added as a padding".
