### ISSUE TITLE
Bug report: HTTP request operation issue

### ISSUE THREAD

**Issue by Antelox** [gchq/CyberChef#149]
I'm using the new operation **HTTP request** but doesn't work.

_URL_: _http://ip-api.com/json/_
_Mode_: I tried both

_Output_:

```
TypeError: NetworkError when attempting to fetch resource.

This error could be caused by one of the following:
 - An invalid URL
 - Making a cross-origin request to a server which does not support CORS
```

**Comment by tlwr** [comment]
It looks like the browser is blocking it because of mixed content: the page is running over HTTPS and the request is using HTTP. [More information](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default)

```Blocked loading mixed active content “http://ip-api.com/json/”```

If you wish to get your IP address from an API using CyberChef over HTTPS the API must support CORS and service HTTPS requests.

This is a recipe that I have got working:
```
[{"op":"HTTP request","args":["GET","https://icanhazip.com/","","Cross-Origin Resource Sharing",false]}]
```
![image](https://user-images.githubusercontent.com/1482692/26987612-389e4494-4d1a-11e7-9716-375abb8e9e44.png)

**Comment by n1474335** [comment]
@tlwr is right. The only solution is for you to download CyberChef and use it from a non-HTTPS source. I've added a note to the error message about mixed content requests in eda17d1671bac85f7faae871ca6d4ce783ba85ba.
