### ISSUE TITLE
HTML entity encoder is buggy

### ISSUE THREAD

**Issue by mathiasbynens** [gchq/CyberChef#15]
Astral Unicode symbols such as `𝌆` are incorrectly encoded as two separate entities (one for each surrogate half).

E.g. `𝌆` becomes `&#55348;&#57094;` instead of `&119558;` or `&#x1D306;`.

https://gchq.github.io/CyberChef/?recipe=%5B%7B"op"%3A"To%20HTML%20Entity"%2C"args"%3A%5Bfalse%2C"Named%20entities%20where%20possible"%5D%7D%5D&input=Zm9vIPCdjIYgYmFy

Perhaps you could use https://github.com/mathiasbynens/he for HTML entity encoding/decoding.

**Comment by n1474335** [comment]
Thanks for pointing this out. I've added support for astral unicode to the core charcode operations so that all operations that utilise them will now support it. This includes 'To/From HTML Entity' as well as 'To/From Charcode'. I've linked to [your blog on the subject](https://mathiasbynens.be/notes/javascript-unicode) in the comments.
