### ISSUE TITLE
Operation request: Chinese version

### ISSUE THREAD

**Issue by Z2549** [gchq/CyberChef#1660]
I have Chinese translation for version 10.5.2, about 94% partially translated, I hope I can add the introduction in README.md in the project, so that more people can use it.thanks
Repository address : https://github.com/Z2549/CyberChef_Chinese
If I have violated the open source agreement or infringed the rights of the original author, please let me know!
Email : Zimerence@outlook.com

**Comment by chixiaome** [comment]
赞！

**Comment by Raka-loah** [comment]
That's 94% partially translated **UI and operation description** right? And partially using **machine translation**? You know you can't do much more without touching the moving parts of CyberChef.
I've done this long time ago (translating the literal strings is the easiest part since that won't break anything and can be automated) and it is just NOT enough. If someone can use CyberChef with operation name and arguments in English, they will do fine without a Chinese UI.

**Comment by a3957273** [comment]
Thanks for taking the time to translate CyberChef into Chinese!  I am not a lawyer, but we're Apache 2.0 licensed, so in terms of forking our code base and changing it to support Chinese you should be A-Okay!  The only issue you may have is with the 'CyberChef' name, which is probably a trademark of GCHQ.  I'd generally be keen for it not to be mistaken for an official version supported by GCHQ.

From a technical perspective, I'm not sure how supportable a "point in time" translation of the entirety of CyberChef is.  We update regularly (when there's a maintainer around) and I worry your version will quickly get out of date.  Really, the best solution would probably be for the base version of CyberChef to support internalization, but supporting that with such a large, existing code base would be a very scary and long endeavor for anyone to take on.

I'm going to close this issue, but feel free to get in touch in the future if you have any thoughts on improving this.  I'm definitely open to supporting a wider range of languages.
