### ISSUE TITLE
XOR Differential

### ISSUE THREAD

**Issue by superhac** [gchq/CyberChef#17]
I'm trying something very simple and I can't figure out if the flaw is on me or on them.

1. Take a base64 encoded payload as Input: "AAAAI9Dw0qHYq9+61/XPtJS20bTAn+yV5o/hh+jK8J7rh+vLtpbr". I use the "From Base64" module. 

2. The result is differential XOR crypt. The seed is 171. I select the XOR module and use 171 as the key. Then i pick "differential" option. Doesn't work.

Recipe: 
[{"op":"From Base64","args":["A-Za-z0-9+/=",false]}
{"op":"Drop bytes","args":["0","4",false]}
{"op":"XOR","args":[{"option":"Hex","string":"AB"},false,true]}]

Am I missing something? This is a very simple example.

The simple python code that decodes it is this:

def decrypt(string): 
    key = 171 
    result = "" 
    for i in string:
      a = key ^ ord(i) 
      key = ord(i) 
      result += chr(a) 
    return result

string = "AAAAKtDygfiL/5r31e+UtsWg1Iv5nPCR6LfEsNGlwOLYo4HyhueT9tTu36Lfog=="
result = decrypt(base64.b64decode(string)[4:])
print "decoded: ", result 
print "Length: " , struct.unpack("I", string[0:4])

**Comment by cadnce** [comment]
```
import base64
import struct

def decrypt(string):
        key = 171
        result = ""
        for i in string:
                a = key ^ ord(i)
                key = ord(i)
                result += chr(a)
        return result

string = "AAAAKtDygfiL/5r31e+UtsWg1Iv5nPCR6LfEsNGlwOLYo4HyhueT9tTu36Lfog=="
result = decrypt(base64.b64decode(string)[4:])
print "decoded: ", result
print "Length: " , struct.unpack("I", string[0:4])
```

**Comment by n1474335** [comment]
Hi @superhac,

The type of differential you implemented was slightly different from the one in CyberChef. In the CyberChef differential, the key was set to the value of the previous byte, after it had been XOR'd. In yours, it is set to the value of the previous byte, before it has been XOR'd.

To alleviate this confusion, I have modified the XOR operation so that it supports both versions and I've named them "Input differential" and "Output differential" to distinguish between them.

Your example now correctly decodes [using the "Output differential" method](https://gchq.github.io/CyberChef/?recipe=%5B%7B%22op%22%3A%22From%20Base64%22%2C%22args%22%3A%5B%22A-Za-z0-9%2B%2F%3D%22%2Ctrue%5D%7D%2C%7B%22op%22%3A%22XOR%22%2C%22args%22%3A%5B%7B%22option%22%3A%22Hex%22%2C%22string%22%3A%22AB%22%7D%2C%22Output%20differential%22%2Cfalse%5D%7D%5D&input=QUFBQUt0RHlnZmlMLzVyMzFlK1V0c1dnMUl2NW5QQ1I2TGZFc05HbHdPTFlvNEh5aHVlVDl0VHUzNkxmb2c9PQ).

**Comment by superhac** [comment]
Hi @n1474335.

That works perfectly when setting the scheme to "Output differential".  I do have one question with regards to the labeling and description of both the differential options.   Per your description the options are as follows:

Input differential: key is set to the value of the previous unprocessed byte
Output differential: key is set to the value of the previous processed byte

If I understand this correctly the input differential happens prior to XORing and the output differential happens after XORing processing.  If thats correct then it seems backwards for the example I provided.   In the example the "next" key is the previous byte prior to XORing.  So on the decoding side its backwards, but for encoding the logic description works.  Maybe the description could be clarified based on input being encoded or decoded.   

Thanks again for the fix!

**Comment by n1474335** [comment]
You're absolutely right. The wording is a little ambiguous depending on whether you're encoding or decoding. I have some more schemes to add soon so I will review the terminology at that point.
