### ISSUE TITLE
Feature request: Copy to clipboard

### ISSUE THREAD

**Issue by Isanderthul** [gchq/CyberChef#198]
It would be convenient if I was able to click on a button in the output that would copy the contents into my clipboard.

**Comment by n1474335** [comment]
I've implemented a "Copy output" button. Rather than just copying the output as it appears in the output textarea, it copies the raw `dishStr`, which is the internal representation of the data before it is run through the `Utils.printable()` function. This function replaces characters that can't be printed properly with dots.

This means that you can copy the actual data, instead of the dots used to represent it.

Unfortunately, this still falls foul of the [`\r` textarea problem](https://stackoverflow.com/a/14217315/7200497). Any `\r` in the data will be converted to `\n` by the browser when added to a textarea. There doesn't seem to be a way of copying data to the clipboard without putting it in a textarea first, so this problem will persist until there is a way around that. If you need to copy binary data, I would recommend always converting it to hex first.

**Comment by Isanderthul** [comment]
Thank you! You were super fast, and the functionality is awesome.
