### ISSUE TITLE
User input is disclosed to web server

### ISSUE THREAD

**Issue by JoshBrodieNZ** [gchq/CyberChef#21]
With the setting "Update the URL when the input or recipe changes" turned on (the default), each update of the URL results in Chrome 54.0.2840.99m on Win10 rerequesting the favicon. 

As a result, user input including parameters supplied to operations such as cryptographic keys are disclosed to the server via URL parameters in the Referer header. This is inconsistent with the feature statement "it should be noted that none of your input or recipe configuration is ever sent to the CyberChef web server". Worth noting to paranoid users that the web server in this instance belongs to GitHub, not to the GCHQ.

Perhaps these parameters could be moved into client-side hash parameters or this setting turned off by default and a warning provided when turned on?

**Comment by n1474335** [comment]
Hi @JoshBrodieNZ,

I'm having trouble replicating this. Is this something you have observed CyberChef doing or something you expect to happen whenever any URL is updated? CyberChef uses the `window.history.replaceState()` method which shouldn't make any requests at all - it simply updates the current URL state.

[This question](https://stackoverflow.com/questions/36103904/history-pushstate-in-chrome-make-favicon-request) on Stack Overflow seems to suggest that it happens when using the `pushState()` method and there seems to be a simple workaround by specifying the favicon as a data URL, which I'll happily do if it turns out that CyberChef is actually making these requests, but I can't see anything being sent in Chrome dev tools or Wireshark. Happy to be proven wrong though!

**Comment by JoshBrodieNZ** [comment]
Thanks for the quick reply. Found another prerequisite. I've reproduced this on two machines now - the user needs to be using incognito mode and have the favicon cleared from their cache.

**Comment by n1474335** [comment]
I'm afraid I'm still unable to replicate this, even with all those prerequisites in place. However, I've applied the workaround [discussed here](http://stackoverflow.com/a/36104057/7200497) and changed the favicon to a data URL anyway so it should no longer be a problem.

**Comment by JoshBrodieNZ** [comment]
Cheers! That seems to have stopped the rerequesting behaviour I was seeing.
