### ISSUE TITLE
ToHex + FromHexDump omits the last character

### ISSUE THREAD

**Issue by QuteBits** [gchq/CyberChef#23]
just adding ToHex + FromHexDump after eachother should return the input as it forms an identity function. In CyberChef it returns the input without the last character.

Example: 'hello' -> 'hell'

**Comment by n1474335** [comment]
Hi @QuteBits,

The reverse function for 'To Hex' is 'From Hex', not 'From Hexdump'. If you use 'From Hex', you'll get [the answer you're looking for](https://gchq.github.io/CyberChef/?recipe=%5B%7B%22op%22%3A%22To%20Hex%22%2C%22args%22%3A%5B%22Space%22%5D%7D%2C%7B%22op%22%3A%22From%20Hex%22%2C%22args%22%3A%5B%22Space%22%5D%7D%5D&input=aGVsbG8).

Hexdumps have very specific formats and although the 'From Hexdump' operation is designed to work with as many of them as possible, it won't work with all. The data you've created isn't a full hexdump which is why it doesn't work correctly.

Hope that helps.
