### ISSUE TITLE
Feature Request: Debounce input entry for JSON

### ISSUE THREAD

**Issue by GCHQ77703** [gchq/CyberChef#345]
Otherwise, whilst you're writing JSON you get a few hundred errors pop up on the screen.

**Comment by n1474335** [comment]
You can manually turn off 'Auto bake' if this is a problem. To debounce JSON, we'd have to detect that the input is JSON, or detect that the first operation in the recipe expects JSON. This would be possible, but I'm not sure how much it really buys us. I assume most people will be pasting JSON in anyway, rather than writing it manually.

**Comment by GCHQ77703** [comment]
Cool solution, thanks.
