### ISSUE TITLE
Bug report: Pale Moon / user agent discrimination

### ISSUE THREAD

**Issue by Gordon-Dry** [gchq/CyberChef#407]
Well, I use Pale Moon for years now and every week I stumble upon these websites which just say
"Huuuh, you no have Chrome or bs Firefox new age, huuuuh." and so regret to support that non-mainstream browser.
Fuck that.

**Comment by n1474335** [comment]
CyberChef is a fairly large, complex web app that uses a lot of the most recent web technologies. If we spent our time ensuring support for every possible browser, we would never write anything new. I decided a while back not to invest time attempting to support anything other than the most popular, standards-compliant browsers (which combined account for the vast majority of users) so that we can keep moving forwards with new capabilities and features.

As it happens, Pale Moon maintains compatibility with Firefox's Gecko rendering engine so CyberChef works perfectly well in it.

Please refrain from using profanity when commenting on this repository. We welcome challenge and debate, but it must be compatible with our [Code of Conduct](https://github.com/gchq/CyberChef/blob/master/CODE_OF_CONDUCT.md).
