### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jeffli678** [gchq/CyberChef#482]
### Summary

Generate a script or source code to perform the current recipe. 

Given the project is written in HTML + JS, it should not be very difficult to generate a js function that takes the input as a parameter and produce the output, exactly as the recipe does. This could drastically shorten my workflow as sometimes after I prototype a reverse engineered algorithm, I still have to implement it from scratch. If CyberChef can generate a function, I directly get what I need. 

If this feature is welcomed, I would suggest devising an interface to allow volunteers to implement the individual algorithms in other languages (e.g., Python), then CyerChef can generate a source directly in that language. I hope I explained what I am suggesting.

**Comment by n1474335** [comment]
Hi @jeffli678, thanks for the suggestion.

I have wanted to implement this for years. Unfortunately it isn't quite as simple as it sounds due to imports, data type conversions etc. However, I do absolutely intend to add it once the NodeAPI work has been merged in #291. This will make the process much easier. I envisage a tab in the "Save recipe" pane that shows a simple script that imports the cyberchef npm package and executes your current recipe.

Re-implementing all 280+ operations in Python would be awesome, but perhaps not the best use of time. Instead, I think a CyberChef RESTful API would offer more bang for its buck. You could then query this remotely from Python if you wanted to. This is something we're working on. Watch this space.
