### ISSUE TITLE
Operation request: Fletcher-32 and -64 checksums

### ISSUE THREAD

**Issue by n1474335** [gchq/CyberChef#51]
**Request summary**

Development of operations to calculate Fletcher-32 and Fletcher-64 checksums. CyberChef already supports Fletcher-16 ([example ](https://gchq.github.io/CyberChef/?recipe=%5B%7B%22op%22%3A%22Fletcher-16%20Checksum%22%2C%22args%22%3A%5B%5D%7D%5D&input=VGVzdA)and [code](https://github.com/gchq/CyberChef/blob/master/src/js/operations/Checksum.js#L12)).

**Example input and output**

*Fletcher-32*
Input: Test
Output: 03d901a0

*Fletcher-64*
Input: Test
Output: Currently unavailable

**Resources**

[https://en.wikipedia.org/wiki/Fletcher%27s_checksum](https://en.wikipedia.org/wiki/Fletcher%27s_checksum)

**Comment by 0xTowel** [comment]
@n1474335 
Is there a reason for doing the operations byte-wise, even with 32-bit sums in `Fletcher64`? Reading the Wikipedia page, it seems as if operations should work on the data as 32-bit chunks, but the original paper from Fletcher doesn't address sizes greater than Fletcher16.

For example, `Fletcher64('AAAABBBB')` as `0xc4c4c4c483838383` rather than `0x92e0000020c`.
