### ISSUE TITLE
Add "%" delimiter option to "From Hex"

### ISSUE THREAD

**Issue by apolkosnik** [gchq/CyberChef#56]
JS unescape() decodes hex values prepended with "%". It would be nice to have.

**Comment by n1474335** [comment]
Hi @apolkosnik,

Hex values prefixed with '%' are a special case known as '[URL encoding](https://en.wikipedia.org/wiki/Percent-encoding)' or 'Percent-encoding'. CyberChef handles this using the 'URL encode' and 'URL decode' operations.

For example: https://gchq.github.io/CyberChef/?recipe=%5B%7B%22op%22%3A%22URL%20Decode%22%2C%22args%22%3A%5B%5D%7D%5D&input=SGVsbG8lMkMlMjB3b3JsZCUyMQ

Using 'URL decode' is preferable to 'From Hex' in this situation because it helpfully ignores characters which are not encoded. 'From Hex' would try to treat everything as hex and mess things up.

I'll close this issue now, but may add the ability to specify custom delimiters for 'To Hex' and 'From Hex' in future.
