### ISSUE TITLE
Issues with Unique and HTML Strip

### ISSUE THREAD

**Issue by indigion** [gchq/CyberChef#7]
Neither of these operations perform as I would expect.
Unique does not delete a duplicate.
HTML Strip removes all text between angle brackets and not just valid HTML tags.

![chef](https://cloud.githubusercontent.com/assets/19506112/20685436/5f82a4ca-b5ac-11e6-85a7-94a813af7248.png)

**Comment by n1474335** [comment]
Hi indigion,

The reason the 'Unique' operation isn't working is because you have padded the commas with spaces. It's trying to compare "one" with " one", which technically isn't the same thing. [If you remove the spaces, you'll see that it correctly uniques the list.](https://gchq.github.io/CyberChef/?recipe=%5B%7B%22op%22%3A%22Unique%22%2C%22args%22%3A%5B%22Comma%22%5D%7D%5D&input=b25lLG9uZSx0d28)

The 'Strip HTML tags' operation is fairly basic. [It just looks for anything between angled brackets](https://github.com/gchq/CyberChef/blob/master/src/js/core/Utils.js#L863). This could potentially be improved, but it's expected to be sufficient for most use cases.

**Comment by indigion** [comment]
Thanks for the response.
Perhaps the description for Strip HTML could be re-worded to indicate the actual functionality better?

**Comment by n1474335** [comment]
Good suggestion, I'll add something in a future update.

**Comment by indigion** [comment]
Sorry to be a pain to re-open but Unique only seems to work with very simple input. Anything complex and it still fails.  Is it confused by a preceding linefeed (\n)?

![gchq2](https://cloud.githubusercontent.com/assets/19506112/20711742/1fd76f9e-b639-11e6-83f0-c52825b7cdd1.png)

![gchq3](https://cloud.githubusercontent.com/assets/19506112/20711961/1b1396b2-b63a-11e6-9c3f-aaa5a3ccc14a.png)

**Comment by n1474335** [comment]
Unique splits up the entire input around the commas, so in your last example it will be comparing the following four strings:

1. "<p>\none"
2. "one"
3. "two"
4. "three\n</p>"

It's a similar case with your other examples. None of these strings are duplicates, so it doesn't remove anything. You'll need to extract only the line you want to unique with no surrounding data to make it work as you want.

**Comment by indigion** [comment]
I guess this needs to be a feature request for a more intelligent Unique then.
