### ISSUE TITLE
Does the "Download Cyber chef" button work for anyone else?

### ISSUE THREAD

**Issue by Faiz7412** [gchq/CyberChef#8]
I was expecting this tool to be available for offline use when clicking on download button. But it doesn't respond.

**Comment by n1474335** [comment]
If you take a look at the URL, you'll notice that the link takes you to [cyberchef.htm](https://raw.githubusercontent.com/gchq/CyberChef/master/build/prod/cyberchef.htm), which is an inlined version of CyberChef, all compiled into a single HTML file. There is a [.htaccess file](https://github.com/gchq/CyberChef/blob/master/build/prod/.htaccess#L3) which specifies that .htm files be downloaded by the client rather than rendered, however this doesn't work with GitHub Pages as they don't use Apache so it just opens it in your browser like any other web page.

If you want to download it, a quick workaround would be to simply right click the link and 'save as'. I might add a popover to the link explaining this to make it a bit more clear. If anyone has ideas for how to easily download the inlined version rather than rendering it (that will work on GitHub Pages), I'd be interested to hear them. One option might be to put it in a zip file.

**Comment by robinwhittleton** [comment]
Will be fixed by https://github.com/gchq/CyberChef/pull/12

**Comment by n1474335** [comment]
GitHub Pages updated with the fix, thanks. Closing.
